// <auto-generated />
using CsjSistemas.LocaisReciclagem.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CsjSistemas.LocaisReciclagem.Data.Migrations
{
    [DbContext(typeof(LocaisReciclagemContext))]
    partial class LocaisReciclagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CsjSistemas.LocaisReciclagem.Domain.Entity.LocaisReciclagem", b =>
                {
                    b.Property<long>("LocalReciclagem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CEP")
                        .HasColumnType("varchar(10)");

                    b.Property<double>("Capacidade")
                        .HasColumnType("float");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Identificacao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Latitude")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Longitude")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroEndereco")
                        .HasColumnType("varchar(10)");

                    b.HasKey("LocalReciclagem_Id");

                    b.ToTable("LocaisReciclagem");
                });
#pragma warning restore 612, 618
        }
    }
}
